TRANSLATIONS = {
    'en': {
        'page_title': 'Mr. Mill CleanTone',
        'switch_language': 'Переключитися на українську',
        'switch_theme': 'Switch to Dark Theme',
        'drag_drop': 'Drag and drop your video file here or click to browse',
        'enhance_video': 'Enhance audio on video',
        'enhance_audio': 'Enhance audio',
        'get_audio_from_video': 'Get audio from video',
        'file_uploaded': 'File successfully uploaded!',
        'invalid_file': 'Invalid file type. Please upload a video file.',
        'video_processed': 'Video processed successfully!',
        'no_file_selected': 'No video file selected. Please upload a file first.',
        'registration': 'Registration',
        'login': 'Log in',
        'logout': 'Log out',
        'my_account': 'My Account',
        'username': 'Username',
        'password': 'Password',
        'selected_plan': 'Selected Plan',
        'registration_successful': 'Registration successful! You can now log in.',
        'user_exists': 'User already exists. Please log in.',
        'login_successful': 'Login successful! Welcome back.',
        'invalid_credentials': 'Invalid credentials. Please try again.',
        'Return_to_Main_Page': 'Return to Main Page',
    },
    'uk': {
        'page_title': 'Mr. Mill CleanTone',
        'switch_language': 'Switch to English',
        'switch_theme': 'Переключитися на темну тему',
        'drag_drop': 'Перетягніть відео сюди або натисніть для вибору файлу',
        'enhance_video': 'Покращити аудіо у відео',
        'enhance_audio': 'Покращити аудіо',
        'get_audio_from_video': 'Отримати аудіо з відео',
        'file_uploaded': 'Файл успішно завантажено!',
        'invalid_file': 'Невірний тип файлу. Завантажте відеофайл.',
        'video_processed': 'Відео успішно оброблено!',
        'no_file_selected': 'Відеофайл не вибрано. Спочатку завантажте файл.',
        'registration': 'Реєстрація',
        'login': 'Увійти',
        'logout': 'Вийти',
        'my_account': 'Мій аккаунт',
        'username': 'Ім\'я користувача',
        'password': 'Пароль',
        'selected_plan': 'Обраний тариф',
        'registration_successful': 'Реєстрація успішна! Тепер ви можете увійти.',
        'user_exists': 'Користувач вже існує. Увійдіть у систему.',
        'login_successful': 'Вхід успішний! Ласкаво просимо назад.',
        'invalid_credentials': 'Неправильні дані. Спробуйте ще раз.',
        'Return_to_Main_Page': 'Повернутися на головну сторінку',
    }
}
